[package]
name = "formatter-rs"
version = "0.1.0"
authors = ["Mohammad Aadil Shabier <64919407+aadilshabier@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
